name: Python Version Check

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Check Python version
        run: python --version

      - name: Run Python file
        run: python main.py
